### ISSUE TITLE
Microservice - notifications broken

### ISSUE THREAD

**Issue by cdhanna** [beamable/BeamableProduct#3323]
https://disruptorbeam.slack.com/archives/C02TH8F7Z2L/p1713412572268549

Coincidentally discovered this while doing some testing ahead of tonight’s release: invoking the notifications api from a unity microservice crashes the container.
Reproduced with local container
Reproduced with remote container (running on beamable)
Reproduced on 1.19.17
Reproduced with 1.19.15
Reproduced on production and staging

Unity code
```csharp
    public async void OnButtonPressed()
    {
        var client = BeamContext.Default.Microservices().HelloWorld();
        await client.TestNotifications("test.update");
    }
```

C#MS code
```csharp
		[ClientCallable]
		public async void TestNotifications(string channel)
		{
			await Services.Notifications.NotifyPlayer(
				Context.UserId, 
				channel, 
				"my test message"
			);
		}
```

error,
```
Beamable.Common.Dependencies.ServiceScopeDisposedException: Provider scope has been destroyed and can no longer be accessed. method=[CanBuildService] type=[ICustomSerializer`1]
   at Beamable.Common.Promise`1.GetResult() in /Client/client/Packages/com.beamable/Common/Runtime/Promise.cs:line 445
   at Beamable.Server.Api.Notifications.NotificationRequestBuilder.SendPlayer(INotificationApi api) in /src/Api/Notifications/MicroserviceNotificationsApi.cs:line 151
   at Beamable.Common.Promise`1.GetResult() in /Client/client/Packages/com.beamable/Common/Runtime/Promise.cs:line 445
   at Beamable.Microservices.HelloWorld.TestNotifications(String channel) in /subapp/helloworld/Beamable.Microservice.HelloWorld/HelloWorld.cs:line 27
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

failed request log
```
2024-04-17 23:52:25 {"__t":"2024-04-18T03:52:25.8735532Z","__m":"Handling TestNotifications","__l":"Debug","requestContext":{"cid":"1468242222494837","pid":"DE_1468242222494838","path":"B0D5F149-2E15-50CD-B7AE-CECF37FAE248micro_HelloWorld/TestNotifications","status":0,"id":1,"isEvent":false,"userId":1502875356176659,"scopes":[]}}
2024-04-17 23:52:30 {"__t":"2024-04-18T03:52:30.0849504Z","__m":"sending request {\"id\":-7,\"method\":\"post\",\"path\":\"basic/notification/player\",\"from\":1502875356176659,\"body\":{\"dbid\":1502875356176659,\"payload\":{\"context\":\"test.update\",\"messageFull\":\"{\\\"stringValue\\\":\\\"my test message\\\"}\"}}","__l":"Debug"}
2024-04-17 23:52:30 {"__t":"2024-04-18T03:52:30.3886852Z","__m":"Unhandled exception. type=[ServiceScopeDisposedException]","__l":"Fatal"}
```

**Comment by allister-beamable** [comment]
I have partial reproduction of this issue on my AllisterTest realm. Sometimes notifications just work, but sometimes they fail silently, and I have not found any rhyme or reason to the difference other than that it seems to be consistent for the lifetime of a deployment. That is, redeploying my C#MS changes the state between "notifications work" and "notifications do not work" but it only _sometimes_ goes to "do not work".

My code for notification testing is as follows...
Server side:
```csharp
[ClientCallable]
public async Task CauseNotification()
{
	Debug.Log("Received CauseNotification call");
	var random = new Random();
	var number = random.Next();
	await Services.Notifications.NotifyPlayer(Context.UserId, "my_notification",
		$"single recipient number={number}");
}
```

Client side:
```csharp
private async void Start()
{
	var ctx = await BeamContext.Default.Instance;
	ctx.Api.NotificationService.Subscribe("my_notification", ReceiveNotification);
	CauseNotificationButton.onClick.AddListener(CauseNotification);
}

private void ReceiveNotification(object obj)
{
	Display("Notification received:\n");
	if (obj is ArrayDict dict)
	{
		Display("(found ArrayDict): ");
		foreach (var kvp in dict)
		{
			Display($"{kvp.Key} = {kvp.Value}");
		}
	}
	else
	{
		Display("(generic object): ");
		Display(obj.ToString());
	}
}

private async void CauseNotification()
{
	ClearDisplay();
	Display("BEGIN CauseNotification()");
	var client = new BoxMicroserviceClient();
	switch (RecipientStyle)
	{
		case RecipientStyle.Single:
			Display("Invoking CauseNotification() remotely.");
			await client.CauseNotification();
			break;
		case RecipientStyle.List:
			Display("Invoking CauseNotificationListLong() remotely.");
			await client.CauseNotificationListLong();
			break;
		default:
			throw new ArgumentOutOfRangeException();
	}

	Display("END CauseNotification()");
}
```
