### ISSUE TITLE
cannot create common-lib

### ISSUE THREAD

**Issue by cdhanna** [beamable/BeamableProduct#3383]
I created a SAM called `SplitTest`, 
```
chrishanna@Chriss-MacBook-Pro-2 SplitTest % ls -a
.               ..              .beamable       .idea           SplitTest.sln   services
```

But when I try to create a common-lib, it doesn't work.

```
chrishanna@Chriss-MacBook-Pro-2 SplitTest % beam project new common-lib Toast
Value cannot be null. (Parameter 'path1')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at cli.Commands.Project.NewCommonLibraryCommand.Handle(CreateCommonLibraryArgs args) in /home/runner/work/BeamableProduct/BeamableProduct/cli/cli/Commands/Project/NewCommonLibraryCommand.cs:line 34
```

This happens even if I pass the `--sln ./SplitTest.sln`

**Comment by cdhanna** [comment]
also hit a deploy bug, 
```
chrishanna@Chriss-MacBook-Pro-2 SplitTest % beam services deploy         
Value cannot be null. (Parameter 'path2')
   at Beamable.Common.Promise`1.GetResult() in /home/runner/work/BeamableProduct/BeamableProduct/cli/beamable.common/Runtime/Promise.cs:line 453
   at cli.ServicesDeployCommand.Handle(ServicesDeployCommandArgs args) in /home/runner/work/BeamableProduct/BeamableProduct/cli/cli/Commands/Services/ServicesDeployCommand.cs:line 107

```
