### ISSUE TITLE
CLI - beam project new service -i not accepting --host option

### ISSUE THREAD

**Issue by gabrielbeamable** [beamable/BeamableProduct#3418]
When running `beam project new service <name> -i --host=dev` in a new workspace and it returns an error for wrong URL.

logs
```
An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.

An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
   at Beamable.Common.Promise`1.GetResult() in /Users/gabrielramos/Projects/BeamableProduct/cli/beamable.common/Runtime/Promise.cs:line 453
   at cli.InitCommand.GetResult(InitCommandArgs args) in /Users/gabrielramos/Projects/BeamableProduct/cli/cli/Commands/InitCommand.cs:line 70
   at cli.AtomicCommand`2.Handle(TArgs args) in /Users/gabrielramos/Projects/BeamableProduct/cli/cli/CommandContext.cs:line 115
   at cli.Commands.Project.SolutionCommandArgs.CreateConfigIfNeeded(InitCommand command) in /Users/gabrielramos/Projects/BeamableProduct/cli/cli/Commands/Project/NewMicroserviceCommand.cs:line 113
   at Beamable.Common.Promise`1.GetResult() in /Users/gabrielramos/Projects/BeamableProduct/cli/beamable.common/Runtime/Promise.cs:line 451
   at cli.Commands.Project.NewMicroserviceCommand.Handle(NewMicroserviceArgs args) in /Users/gabrielramos/Projects/BeamableProduct/cli/cli/Commands/Project/NewMicroserviceCommand.cs:line 179
   at cli.DependencyInjectionExtensions.<>c__DisplayClass3_0`3.<<AddSubCommandWithHandler>b__1>d.MoveNext() in /Users/gabrielramos/Projects/BeamableProduct/cli/cli/DependencyInjectionExtensions.cs:line 78
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<AddMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by cdhanna** [comment]
I think we removed the `-i` flag in favor of splitting the act of workspace creation from the act of project C#MS creation. However, we should still test this.

**Comment by cdhanna** [comment]
actually, this is done.
