### ISSUE TITLE
CLI QA - `beam services run` didn't give storage connstr to service correctly. 

### ISSUE THREAD

**Issue by cdhanna** [beamable/BeamableProduct#3425]
I had no containers running, 
and I had a service that depends on a storage. 

Then I ran
```
beam services run --ids Window
```
and I also tried this with
```
beam services run 
```

But I get this error, 
```

[Exception] Docker.DotNet.DockerContainerNotFoundException Docker API responded with status code=NotFound, response={"message":"No such container: CanOfWorms_mongoDb"}
    at Docker.DotNet.ContainerOperations.<>c.<.cctor>b__30_0(HttpStatusCode statusCode, String responseBody)
   at Docker.DotNet.DockerClient.HandleIfErrorResponseAsync(HttpStatusCode statusCode, HttpResponseMessage response, IEnumerable`1 handlers)
   at Docker.DotNet.DockerClient.MakeRequestAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
   at Docker.DotNet.ContainerOperations.InspectContainerAsync(String id, CancellationToken cancellationToken)
   at cli.Services.BeamoLocalSystem.GetStorageHostPort(String storageName) in /home/runner/work/BeamableProduct/BeamableProduct/cli/cli/Services/BeamoLocalSystem_HttpMicroservice.cs:line 52
   at Beamable.Common.Promise`1.GetResult() in /home/runner/work/BeamableProduct/BeamableProduct/cli/beamable.common/Runtime/Promise.cs:line 451
   at cli.Services.BeamoLocalSystem.GetLocalConnectionString(BeamoLocalManifest localManifest, String storageName, String host) in /home/runner/work/BeamableProduct/BeamableProduct/cli/cli/Services/BeamoLocalSystem_HttpMicroservice.cs:line 71
   at cli.Services.BeamoLocalSystem.RunLocalHttpMicroservice(BeamoServiceDefinition serviceDefinition, HttpMicroserviceLocalProtocol localProtocol, BeamoLocalSystem localSystem) in
/home/runner/work/BeamableProduct/BeamableProduct/cli/cli/Services/BeamoLocalSystem_HttpMicroservice.cs:line 142


```

When I do a `docker inspect Window_httpMicroservice`, I don't see the connection string in the ENV vars. 

----

**Comment by gabrielbeamable** [comment]
This is weird, is there more specifics about this? Because I just created a new organization, created a service and storage and both started just fine in docker with `beam services run --ids <service>`

**Comment by cdhanna** [comment]
yeah, I wasn't able to reproduce this on 2.0.1 rc1.
