### ISSUE TITLE
CLI - content pull failed for realm with two manifests

### ISSUE THREAD

**Issue by cdhanna** [beamable/BeamableProduct#3460]
I have a realm with two content manifests, `global` and `test2`. I haven't touched this realm in a long time, but hey, it exists... 

this was on latest main when this ticket was written, I was using a nightly version I'd built. https://www.nuget.org/packages/Beamable.Tools/0.0.0-PREVIEW.NIGHTLY-202406041313

I started a new beam workspace, 

```
beam init AliDay
cd AliDay
beam content pull
```

And I got an error, 
```
chrishanna@Chriss-MacBook-Pro-2 AliDay % beam content pull
Tags file not found, using empty one

Tags file not found, using empty one

Object reference not set to an instance of an object.
   at Beamable.Common.Promise`1.GetResult() in /home/runner/work/BeamableProduct/BeamableProduct/cli/beamable.common/Runtime/Promise.cs:line 453
   at cli.Services.Content.ContentService.GetLocalContentForManifests(String[] manifestsToGet) in /home/runner/work/BeamableProduct/BeamableProduct/cli/cli/Services/Content/ContentService.cs:line 201
   at Beamable.Common.Promise`1.GetResult() in /home/runner/work/BeamableProduct/BeamableProduct/cli/beamable.common/Runtime/Promise.cs:line 451
   at cli.Content.ContentPullCommand.GetResult(ContentPullCommandArgs args) in /home/runner/work/BeamableProduct/BeamableProduct/cli/cli/Commands/Content/ContentPullCommand.cs:line 38

```

Full logs attached. 
[failure.txt](https://github.com/user-attachments/files/15552135/failure.txt)

**Comment by cdhanna** [comment]
Some of our customers use multi-content namespaces, but its _mostly_ an unused feature. 

Fixing this ticket may not be worth the effort for now.
